### ISSUE TITLE
Mac installation issue - libnative etc

### ISSUE THREAD

**Issue by enzyme69** [nomelif/Audionodes#13]
<img width="856" alt="screen shot 2018-03-17 at 6 28 50 pm" src="https://user-images.githubusercontent.com/3952687/37552867-1b49ecd4-2a11-11e8-81bd-683aec60b3f2.png">

I got the error message above...

Is this related to PyGame module? Because I cannot install PyGame properly either on my Mac.

I am using Conda Python, I think. My Blender is Python 3.5.4.

**Comment by enzyme69** [comment]
Actually PyGame module is installed okey with all the dependency, I am sure on that.

What I am still not sure is whether to use Blender with Python 3.5.4 or 3.6, and also I don't get this libnative.dylib, image not found....

**Comment by ollpu** [comment]
Hi!

We are no longer using PyGame at all, but have some other dependencies which you should install, refer to the README. The main issue here isn't about the dependencies, though:

We should probably emphasize this more in our instructions (or make a clearer error message), but the addon won't work if you directly download the repository as a zip, since the native backend needs to be compiled. You should instead download a zip from the Releases-page or compile the backend yourself according to the instructions in the README.

**Comment by enzyme69** [comment]
Ok... compile the backend sounds really complicated for me, so I guess I cannot study this one for now sadly. Would be nice to have it working, I am really into synth with nodes like SonicPi, but in Blender. 

I will wait until installation is much simpler on Mac. Thanks!

**Comment by ollpu** [comment]
Oh, you don't have to compile it yourself, just download a copy from the [releases](https://github.com/nomelif/Audionodes/releases)-page.

Compiling manually is only necessary if you want some newer features right now. Hopefully we will make a new release soon. Sorry for my confusing explanation.
