### ISSUE TITLE
VMPK with AudioNodes

### ISSUE THREAD

**Issue by ZackMercury** [nomelif/Audionodes#20]
Restarted my PC, Blender, VMPK, recreated the node, console is empty, the setup is here
https://github.com/nomelif/Audionodes/issues/16#issuecomment-461547470
Nothing happens in AudioNodes, no sounds, just silence.

**Comment by ollpu** [comment]
The velocity wheel seems to be set quite low in the picture, try turning it up max. (even though you haven't plugged anything in the velocity socket, a note with velocity 0 is discarded) And don't forget to recreate the MIDI input node again when you set up.

If still nothing I will have to make a more sophisticated testing build for you, let's see.

**Comment by ZackMercury** [comment]
I turned the velocity down because VMPK was playing it's own instruments which I don't want to hear.
It was on by default, but I still could hear nothing besides the VMPK's instruments.

**Comment by ZackMercury** [comment]
I just set it to 1, it still plays nothing.

**Comment by ZackMercury** [comment]
is this correct? these are the default settings
![image](https://user-images.githubusercontent.com/10474828/52479237-a260c480-2bb0-11e9-8bf6-a4f40a0e0499.png)

**Comment by ollpu** [comment]
Not exactly correct, but that would explain where the built-in synthesizer is coming from. Check `Show Advanced Connections` and see what options are available in `Output MIDI Conncetion`.

I tried it on a Windows virtual machine, but I'm getting 
```
Audionodes Native: Unable to create MIDI device via Fluidsynth
```
in the console, so the issue must be different.

**Comment by ZackMercury** [comment]
Only "Game Controller 1", I tried all 3 settings available there, none of them did work.
No, I did not forget to readd the "MIDI input" node.

**Comment by ollpu** [comment]
What do you mean by the console being empty? Can you post a screenshot of it after creating a MIDI input node?

**Comment by ZackMercury** [comment]
there you go 
![image](https://user-images.githubusercontent.com/10474828/52520880-7bb99100-2c77-11e9-93fd-6f7e3aeeeb58.png)

**Comment by ollpu** [comment]
Thanks. I will make a testing build once I am able to.

**Comment by ollpu** [comment]
I got to my physical Windows computer, and sure enough, it doesn't work. I must've incorrectly remembered testing it at some point. Terribly sorry for the inconvenience and wait.

There seems to be two kinds of MIDI ports in the Windows MIDI mapper, named ones and anonymous, unnamed ones. Neither Audionodes (internally fluidsynth's MIDI API) nor VMPK create a named port, but can only bind to named ports. Hence why they don't like each other.

For now I will recommend using [loopMIDI](http://www.tobias-erichsen.de/software/loopmidi.html), which creates two named ports for input and output and loops the signal around. Create the loop port in loopMIDI and then choose it in VMPK (Edit -> MIDI Setup -> Output MIDI Connection: "loopMIDI Port") and re-create the MIDI input node in the node editor (there clearly should be a button for rebinding the port, I'll add that to the TODO). Let me know if this works for you too.

**Comment by ZackMercury** [comment]
Come on, what inconvenience are you talking about, I'm not paying you anything.
You're not supposed to apologize. 

I did set it all up as you said, I got data throughput traffic happening in realtime, but AudioNodes do not react to it.
I tried restarting Blender, recreating the nodes a couple times, no magic happened.

**Comment by ZackMercury** [comment]
Maybe I need to select a specific output port somewhere?

**Comment by ollpu** [comment]
Interesting. There's no other port selection you should need to do besides VMPK output, Audionodes automatically chooses a default input port. The only available port should be from loopMIDI, but you had that "Game Controller 1" device, right? It might be binding to that instead. You can verify that the "Game Controller 1" also has an output port by selecting `MIDI IN Driver: Windows MM`, and looking at what ports show up in `Input MIDI Connection`. Change the input driver back to `Network` once you're done to not mess up anything else.

If possible, try getting rid of the device responsible for "Game Controller 1". (Device Manager's section for `Sound, video and game controllers` should help) There will be a proper device selection dropdown in Audionodes eventually, sooner rather than later if it is required here.

**Comment by ollpu** [comment]
Interesting. There's no other port selection you should need to do besides VMPK output, Audionodes automatically chooses a default input port. The only available port should be from loopMIDI, but you had that "Game Controller 1" device, right? It might be binding to that instead. You can verify that the "Game Controller 1" also has an output port in VMPK by selecting `MIDI IN Driver: Windows MM`, and looking at what ports show up in `Input MIDI Connection`. Change the input driver back to `Network` once you're done to not mess up anything else.

If possible, try getting rid of the device responsible for "Game Controller 1". (Device Manager's section for `Sound, video and game controllers` should help) There will be a proper device selection dropdown in Audionodes eventually, sooner rather than later if it is required here.

**Comment by ZackMercury** [comment]
It was a virtual device, must have been one of the drivers from some of the audio software I have installed.
I removed it from the device manager and probably I need a restart cause it doesn't seem to disappear from the VMPK's connection settings.

**Comment by ZackMercury** [comment]
I can't get rid of it, whenever I reopen my device manager, it's there again.

**Comment by ollpu** [comment]
Ok, I'll get to doing that input device selection dropdown soon. Always good to have some external motivation :)

**Comment by ollpu** [comment]
Status update:
After some wrestling with Blender's Python API, I am now fairly satisfied with the interface.
![MIDI configuration demo](https://thumbs.gfycat.com/OrdinaryJealousFrenchbulldog-size_restricted.gif)
Now I just need to compile & test on Windows.

**Comment by ollpu** [comment]
Alright, try the [new version](https://github.com/nomelif/Audionodes/releases/tag/v0.3.1). You will still need loopMIDI.

**Comment by ZackMercury** [comment]
Works.

**Comment by ZackMercury** [comment]
Thank you for your support, ollpu.

**Comment by ollpu** [comment]
Good to hear. Closing this issue now.
